apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: capstone
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 8.3.1
    helm.sh/chart: grafana-6.18.2
  name: prometheus-grafana-nodeport
  namespace: capstone
spec:
  type: NodePort
  ports:
  - name: traffic
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 32000
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  