apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: capstone
  labels:
    app: capstone-prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: capstone
    app.kubernetes.io/version: 23.1.1
    chart: kube-prometheus-stack-23.1.1
    heritage: Helm
    release: prometheus
    self-monitor: "true"
  name: prometheus-capstone-prometheus-nodeport
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: http-traffic
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 31000
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: prometheus-capstone-prometheus
  