apiVersion: v1
kind: Service
metadata:
  name: capstone-application
  namespace: capstone
spec:
  type: ClusterIP
  ports:
    - name: traffic
      port: 8080
      targetPort: 8080
  selector:
      app: capstone