apiVersion: v1
kind: Service
metadata:
  name: mongodb-clusterip
  namespace: capstone
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb